#spring.application.name=data-service
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://findmypark.cfwsayiqmgbz.eu-west-1.rds.amazonaws.com:3306/findmyparkdb
    username: admin
    password: gS175WKh
    driver-class-name: com.mysql.cj.jdbc.Driver


  cloud:
    gateway:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
      corsConfigurations:
      "[/**]":
        allowedOrigins: "*"
        allowedMethods: "*"
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.data.service.dataservice.entity
