#spring.application.name=calendar-service
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://findmypark.cfwsayiqmgbz.eu-west-1.rds.amazonaws.com:3306/findmyparkdb
    username: admin
    password: gS175WKh
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  gateway:
  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  globalcors:
    corsConfigurations:
    "[/**]":
      allowedOrigins: "*"
      allowedMethods: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.calendar.service.calendarservice.entity

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
    com.calendar.service.calendarservice: DEBUG

api:
  key: c0RgtRWBSvE8YWBxDwawirsg-MXXeIFyCnIC21AB
  url: https://api.predicthq.com/v1/events
