spring:
  datasource:
    url: jdbc:mysql://findmypark.cfwsayiqmgbz.eu-west-1.rds.amazonaws.com:3306/findmyparkdb
    username: admin
    password: gS175WKh
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.calendar.service.calendarservice.entity

server:
  port: 8080

logging:
  level:
    com.calendar.service.calendarservice: DEBUG

api:
  key: 6diW47J5IrXlZ-Aid4dx75fH3HuzjJcC7H8h61rr
  url: https://api.predicthq.com/v1/events