spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calendar
    username: root
    #    replace password with local MySql password
    password: mariecurie
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  gateway:
  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  globalcors:
    corsConfigurations:
    "[/**]":
      allowedOrigins: "http://localhost:3000"
      allowedMethods: "*"
      allowedCredentials: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.calendar.service.calendarservice.entity

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
    com.calendar.service.calendarservice: DEBUG

api:
  key: 6diW47J5IrXlZ-Aid4dx75fH3HuzjJcC7H8h61rr
  url: https://api.predicthq.com/v1/events
