const activityIcons: { [key: string]: string } = {
  "Arts and Culture": "/icons/icons-art.svg",
  Astronomy: "/icons/astronomy.svg",
  "Auto and ATV": "/icons/icon-atv.svg",
  Biking: "/icons/icons-biking.svg",
  Boating: "/icons/icon-boating.svg",
  "Bookstore and Park Store": "/icons/icon-park.svg",
  Camping: "/icons/icon-camping.svg",
  Canoeing: "/icons/icon-canoeing.svg",
  Caving: "/icons/icon-caving.svg",
  Climbing: "/icons/icon-climbing.svg",
  "Compass and GPS": "/icons/icon-compass.svg",
  "Dog Sledding": "/icons/icon-sledge.svg",
  Dining: "/icons/icon-food.svg",
  Fishing: "/icons/icon-fishing.svg",
  Flying: "/icons/icon-flyfishing.svg",
  Food: "/icons/icon-food.svg",
  Golfing: "/icons/icon-golf.svg",
  "Guided Tours": "/icons/icon-tours.svg",
  "Self-Guided Tours - Walking": "/icons/icon-tours.svg",
  "Hands-On": "/icons/icon-tours.svg",
  Hiking: "/icons/icon-hiking.svg",
  "Horse Trekking": "/icons/icon-horseriding.svg",
  "Hunting and Gathering": "/icons/icon-hunting.svg",
  "Ice Skating": "/icons/icon-iceskating.svg",
  "Junior Ranger Program": "/icons/icon-childrens.svg",
  Kayaking: "/icons/icon-kayaking.svg",
  "Living History": "/icons/icon-historical.svg",
  "Museum Exhibits": "/icons/icons-art.svg",
  Paddling: "/icons/icon-paddling.svg",
  "River tubing": "icon-tubing.svg",
  "Park Film": "/icons/icon-movie.svg",
  Playground: "/icons/icon-playground.svg",
  "SCUBA Diving": "/icons/icon-scuba.svg",
  Shopping: "/icons/icon-shopiing.svg",
  Skiing: "/icons/icon-skiing.svg",
  Snorkeling: "/icons/icon-scuba.svg",
  "Snow Play": "/icons/icon-wintersports.svg",
  Snowmobiling: "/icons/icon-wintersports.svg",
  Snowshoeing: "/icons/icon-wintersports.svg",
  Surfing: "/icons/icon-surf.svg",
  Swimming: "/icons/icon-swim.svg",
  "Team Sports": "/icons/icon-sports.svg",
  Tubing: "/icons/icon-tubing.svg",
  "Water Skiing": "/icons/icon-skiing1.svg",
  "Wildlife Watching": "/icons/icon-wildlifeviewing.svg",
};

export default activityIcons;
