#spring.application.name=profile-service

server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nycparkfinder
    username: root
    password: Shachu@0203
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: nycparkfinderweb@gmail.com
    password: nvxjdsylvvtrzsia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: PROFILE-SERVICE

#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/